In [10]:
# Numeric
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

arr2d = np.array([[1, 2], [2, 7], [3, 9]])
print(arr2d)
print(type(arr2d))

print(arr2d.shape) # (3, 2) -> 3 rows and 2 colums

# normal python
list_of_list = [[1, 2], [2, 7], [3, 9]]
print(list_of_list)
print(type(list_of_list))

arr2 = np.array([2,3,4])
print(arr + arr2) # [3,5,7]
print(arr * arr2) # [2,6,12]
print(arr ** 2) # [1,4,9]
print(arr + 1) # [2 3 4]


[1 2 3]
[[1 2]
 [2 7]
 [3 9]]
<class 'numpy.ndarray'>
(3, 2)
[[1, 2], [2, 7], [3, 9]]
<class 'list'>
[3 5 7]
[ 2  6 12]
[1 4 9]
[2 3 4]


In [21]:
# normal python
list1 = [1,2,3]
print(list1 * 2) # [1, 2, 3, 1, 2, 3]
# print(list1 - 2)
# print(list1 + 2)

[1, 2, 3, 1, 2, 3]


In [16]:
# statistic
arr3 = np.array([100, 8, 6, 4, 99, 80]) # shape 1 row x 6 columns
print(np.mean(arr3))
print(np.std(arr3))
print(np.min(arr3))
print(np.max(arr3))

arr4 = arr3.reshape(2, 3)
print(arr4) # [[100   8   6] [  4  99  80]]

print(arr3.size)
print(arr4.size)


49.5
43.999053020112456
4
100
[[100   8   6]
 [  4  99  80]]
6
6
